name: Python AI/ML Pipeline 

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.7.1"
      
      - name: Install PRODUCTION dependencies
        run: uv pip install -r requirements.txt